### ISSUE TITLE
Crash after `Name or service not known` error

### ISSUE THREAD

**Issue by gchudnov** [kapouer/node-webkitgtk#26]
When running two requests one after the other, If the first request contains a bad URL, the second request crashes the app.

The first request reports an error (as expected):
```
Error: Error resolving 'www.mezilla.org': Name or service not known
    at Error (native)
    at WebKit.<anonymous> (/home/gchudnov/Projects/node-webkitgtk/webkitgtk.js:609:27)
    at Timer.listOnTimeout (timers.js:89:15)
```

The second request terminates the app (unexpected):
```
iojs crashed with SIGSEGV in WebView::PngWrite()
```

Sample code (might be a bit long):
```javascript
var WebKit = require('../');
var expect = require('expect.js');
var fs = require('fs');
var path  = require('path');

describe.only("Experiment", function suite() {
  this.timeout(10000);

  var w;

  before(function(cb) {
    var inst = new WebKit();
    var initOptions = {
      width: 1024,
      height: 768,
      depth: 32
    };

    inst.init(initOptions, function(err) {
      if(err) {
        cb(err);
      } else {
        w = inst;
        cb();
      }
    });
  });


  it("reports an error on Bad URL", function(done) {

    var href = "https://www.mezilla.org/en-US/";
    var filePath = path.resolve(__dirname, './shots/out1.png');

    function onRendered(err) {
      console.log('ON_RENDERED', err);
      console.log('DONE!');
      done();
    }

    w.once('idle', function() {
      w.png(filePath, onRendered);
    });

    var loadParams = {
    };

    w.load(href, loadParams, function(err) {
      if(err) {
        console.log('LOAD_ERROR', err);
        done(err);
      }
    });

  });

  it("should render Good URL after a bad one", function(done) {

    var href = "https://www.mozilla.org/en-US/";
    var filePath = path.resolve(__dirname, './shots/out2.png');

    function onRendered(err) {
      console.log('ON_RENDERED', err);
      console.log('DONE!');
      done();
    }

    w.once('idle', function() {
      w.png(filePath, onRendered);
    });

    var loadParams = {
    };

    w.load(href, loadParams, function(err) {
      if(err) {
        console.log('LOAD_ERROR', err);
        done(err);
      }
    });

  });

});


```

**Comment by kapouer** [comment]
ACK i'll try to fix this asap

**Comment by kapouer** [comment]
You can easily work around that crash if you set the 'idle' listener in the load callback iff there is no error at that stage.

**Comment by kapouer** [comment]
Two successive calls of png() are responsible for the crash.
I've pushed version 1.18.9, making your code throw an exception instead of segfaulting.

**Comment by gchudnov** [comment]
Got it,
Thank you!

**Comment by gchudnov** [comment]
So, it is better to set up `idle` and `load` handlers after `.load` completes without an error. Right?

**Comment by gchudnov** [comment]
In the following code that uses the `async` to print images one after the other, the second `load` callback (marked as '---> LOAD-COMPLETE') is never called:
```
    var arr = [
      "https://www.mezilla.org/en-US/",
      "https://www.google.com"
    ];
    async.eachSeries(arr, function(it, cb) {
      var href = it;
      var filePath = path.resolve(__dirname, './shots/outN.png');
      console.error('---> LOAD', href);
      w.load(href, {}, function(err) {
        console.error('---> LOAD-COMPLETE');
        if(err) {
          console.error('---> LOAD-ERR', err);
          cb();`'---> LOAD-COMPLETE'`
        } else {
          console.error('---> SETTING-IDLE');
          w.once('idle', function() {
            w.png(filePath, function(err) {
              console.error('---> PNG', href, err);
              cb();
            });
          });
        }
      });
    }, function(err) {
      done(err);
    });
```

Not sure what is the problem?

A complete test might something like this:
```
var WebKit = require('../');
var expect = require('expect.js');
var fs = require('fs');
var path = require('path');
var async = require('async');

describe.only("ordered png render calls", function suite() {
  this.timeout(20000);
  var w;
  before(function(cb) {
    var inst = new WebKit();
    inst.init({}, function(err) {
      if (err) return cb(err);
      w = inst;
      cb();
    });
  });
  it("should not stall", function(done) {
    var arr = [
      "https://www.mezilla.org/en-US/",
      "https://www.google.com/",
      "https://www.debian.org/"
    ];
    async.eachSeries(arr, function(it, cb) {
      var href = it;
      var filePath = path.resolve(__dirname, './shots/outN.png');
      console.error('---> LOAD', href);
      w.load(href, {}, function(err) {
        console.error('---> LOAD-COMPLETE');  // <--- callback not called for the second time
        if(err) {
          console.error('---> LOAD-ERR', err);
          cb();
        } else {
          console.error('---> SETTING-IDLE');
          w.once('idle', function() {
            w.png(filePath, function(err) {
              console.error('---> PNG', href, err);
              cb();
            });
          });
        }
      });
    }, function(err) {
      done(err);
    });
  });
});

```
