### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by tugrul** [kapouer/node-webkitgtk#63]
NodeJS: v6.10.0
NPM: 4.3.0
g++: gcc version 4.9.2 (Debian 4.9.2-10) Target: x86_64-linux-gnu
webkitgtk: 4.5.0
OS: Debian GNU/Linux 8.7 (jessie)

WebKitGTK deb package info:
Package: libwebkit2gtk-4.0-dev
Source: webkit2gtk
Version: 2.6.2+dfsg1-4

node-gyp rebuild
```
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
../src/gvariantproxy.cc: In static member function ‘static void GVariantProxy::Init(v8::Handle<v8::Object>)’:
../src/gvariantproxy.cc:121:2: warning: ‘void v8::ObjectTemplate::SetAccessCheckCallbacks(v8::NamedSecurityCallback, v8::IndexedSecurityCallback, v8::Local<v8::Value>)’ is deprecated (declared at /home/threedot/.node-gyp/6.10.0/include/node/v8.h:4801): Use SetAccessCheckCallback instead [-Wdeprecated-declarations]
  );
  ^
../src/webrequest.cc: In static member function ‘static Nan::NAN_GETTER_RETURN_TYPE WebRequest::get_prop(v8::Local<v8::String>, Nan::NAN_GETTER_ARGS_TYPE)’:
../src/webrequest.cc:49:106: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated (declared at /home/threedot/.node-gyp/6.10.0/include/node/v8.h:3274): Use maybe version [-Wdeprecated-declarations]
   Local<Object> obj = Nan::New<FunctionTemplate>(GVariantProxy::constructor)->GetFunction()->NewInstance();
                                                                                                          ^
../src/webresponse.cc: In static member function ‘static Nan::NAN_GETTER_RETURN_TYPE WebResponse::get_prop(v8::Local<v8::String>, Nan::NAN_GETTER_ARGS_TYPE)’:
../src/webresponse.cc:108:107: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated (declared at /home/threedot/.node-gyp/6.10.0/include/node/v8.h:3274): Use maybe version [-Wdeprecated-declarations]
    Local<Object> obj = Nan::New<FunctionTemplate>(GVariantProxy::constructor)->GetFunction()->NewInstance();
                                                                                                           ^
../src/webview.cc: In member function ‘void WebView::unloaded()’:
../src/webview.cc:237:82: error: ‘webkit_user_content_manager_unregister_script_message_handler’ was not declared in this scope
   webkit_user_content_manager_unregister_script_message_handler(contman, "events");
                                                                                  ^
../src/webview.cc: In static member function ‘static gboolean WebView::Authenticate(WebKitWebView*, WebKitAuthenticationRequest*, gpointer)’:
../src/webview.cc:302:106: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated (declared at /home/threedot/.node-gyp/6.10.0/include/node/v8.h:3274): Use maybe version [-Wdeprecated-declarations]
  Local<Object> obj = Nan::New<FunctionTemplate>(WebAuthRequest::constructor)->GetFunction()->NewInstance();
                                                                                                          ^
../src/webview.cc: In static member function ‘static void WebView::ResourceReceiveData(WebKitWebResource*, guint64, gpointer)’:
../src/webview.cc:396:103: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated (declared at /home/threedot/.node-gyp/6.10.0/include/node/v8.h:3274): Use maybe version [-Wdeprecated-declarations]
  Local<Object> obj = Nan::New<FunctionTemplate>(WebResponse::constructor)->GetFunction()->NewInstance();
                                                                                                       ^
../src/webview.cc: In static member function ‘static void WebView::ResourceResponse(WebKitWebResource*, gpointer)’:
../src/webview.cc:416:103: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance() const’ is deprecated (declared at /home/threedot/.node-gyp/6.10.0/include/node/v8.h:3274): Use maybe version [-Wdeprecated-declarations]
  Local<Object> obj = Nan::New<FunctionTemplate>(WebResponse::constructor)->GetFunction()->NewInstance();
                                                                                                       ^
../src/webview.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE WebView::Load(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/webview.cc:671:79: error: ‘webkit_user_content_manager_register_script_message_handler’ was not declared in this scope
  webkit_user_content_manager_register_script_message_handler(contman, "events");
                                                                               ^
make: *** [Release/obj.target/webkitgtk/src/webview.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 3.16.0-4-amd64
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/threedot/node-autoevolution/node_modules/webkitgtk
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok

```

**Comment by kapouer** [comment]
The [webkit_user_content_manager_register_script_message_handler was introduced in webkit2gtk 2.8](https://webkitgtk.org/reference/webkit2gtk/stable/api-index-2-8.html), so i need to fix the README.
Meanwhile you'll have better results using the [version from debian backports](https://packages.debian.org/search?keywords=libwebkit2gtk&searchon=names&section=all&suite=jessie-backports).
