### ISSUE TITLE
 webkitgtk@4.7.0  install error

### ISSUE THREAD

**Issue by 344389541** [kapouer/node-webkitgtk#71]
## ReferenceError: MutationObserver is not defined

`MacBook-Pro:node_test1 ye$ npm install webkitgtk@4.7.0

webkitgtk@4.7.0 install /Users/ye/work/dev/js/node_test1/node_modules/webkitgtk
make || exit 0

node-gyp configure
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
node-gyp build
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  TOUCH Release/obj.target/mkdirs.stamp
  SOLINK_MODULE(target) Release/webkitgtk.node
  SOLINK(target) Release/webextension.dylib
  TOUCH Release/obj.target/action_after_build.stamp
node src/navigator.js > navigator.json
undefined:165
                observer = new MutationObserver(function(mutations) {
                ^

ReferenceError: MutationObserver is not defined
    at trackExternalResources (eval at <anonymous> (/Users/ye/work/dev/js/node_test1/node_modules/webkitgtk/jsdom/index.js:116:11), <anonymous>:165:3)
    at tracker (eval at <anonymous> (/Users/ye/work/dev/js/node_test1/node_modules/webkitgtk/jsdom/index.js:116:11), <anonymous>:98:7)
    at eval (eval at <anonymous> (/Users/ye/work/dev/js/node_test1/node_modules/webkitgtk/jsdom/index.js:116:11), <anonymous>:630:3)
    at eval (<anonymous>)
    at WebKit.<anonymous> (/Users/ye/work/dev/js/node_test1/node_modules/webkitgtk/jsdom/index.js:116:11)
    at exports.jsdom (/Users/ye/work/dev/js/node_test1/node_modules/jsdom/lib/jsdom.js:136:13)
    at WebKit.<anonymous> (/Users/ye/work/dev/js/node_test1/node_modules/webkitgtk/jsdom/index.js:149:14)
    at runCallback (timers.js:756:18)
    at tryOnImmediate (timers.js:717:5)
    at processImmediate [as _immediateCallback] (timers.js:697:5)
make: *** [lib] Error 1
+ webkitgtk@4.7.0
updated 1 package in 7.397s
`

**Comment by kapouer** [comment]
Did you just build webkitgtk on OSX ?
node-webkitgtk is compatible with a fairly recent version of webkit2gtk (like 2.16 or 2.18).

**Comment by 344389541** [comment]
yes, i build webkitgtk on OSX。
